#!/bin/bash
#set -e
##################################################################################################################
# Author 	: Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website	: https://www.arcolinux.info
# Website	: https://www.arcolinux.com
# Website	: https://www.arcolinuxd.com
# Website	: https://www.arcolinuxb.com
# Website	: https://www.arcolinuxiso.com
# Website	: https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black 
#tput setaf 1 = red 
#tput setaf 2 = green
#tput setaf 3 = yellow 
#tput setaf 4 = dark blue 
#tput setaf 5 = purple
#tput setaf 6 = cyan 
#tput setaf 7 = gray 
#tput setaf 8 = light blue
##################################################################################################################
SERVER=$(loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}')


if [[ $SERVER = 'wayland' ]]; then
	echo
	tput setaf 2
	echo "##########################################################"
	echo "###  We are on wayland, change packages .desktop files ###"
	echo "##########################################################"
	tput sgr0
	echo

	echo "Adding QT_QPA_PLATFORM=xcb to the .desktop files"
	echo

	if [ -f /usr/share/applications/dolphin-emu.desktop ]; then
		FIND="Exec=dolphin-emu"
		REPLACE="Exec=\/usr\/bin\/env QT_QPA_PLATFORM=xcb dolphin-emu"
		echo "Changing /usr/share/applications/dolphin-emu.desktop"
		sudo sed -i "s/$FIND/$REPLACE/g" /usr/share/applications/dolphin-emu.desktop
	fi

	if [ -f /usr/share/applications/pcsx2-qt.desktop ]; then
		FIND="Exec=\/opt\/pcsx2\/pcsx2-qt"
		REPLACE="Exec=\/usr\/bin\/env QT_QPA_PLATFORM=xcb \/opt\/pcsx2\/pcsx2-qt"
		echo "Changing /usr/share/applications/pcsx2-qt.desktop"
		sudo sed -i "s/$FIND/$REPLACE/g" /usr/share/applications/pcsx2-qt.desktop
	fi

	if [ -f /usr/share/applications/virtualbox.desktop ]; then
		FIND="Exec=VirtualBox"
		REPLACE="Exec=\/usr\/bin\/env QT_QPA_PLATFORM=xcb VirtualBox"
		echo "Changing /usr/share/applications/virtualbox.desktop"
		sudo sed -i "s/$FIND/$REPLACE/g" /usr/share/applications/virtualbox.desktop
	fi

	#echo
	#echo "Adding GDK_BACKEND=x11 to the .desktop files"
	#echo
	#if [ -f /usr/share/applications/octopi.desktop ]; then
	#	FIND="Exec=\/usr\/bin\/octopi"
	#	REPLACE="Exec=\/usr\/bin\/env GDK_BACKEND=x11 \/usr\/bin\/octopi"
	#	echo "Changing /usr/share/applications/octopi.desktop"
	#	sudo sed -i "s/$FIND/$REPLACE/g" /usr/share/applications/octopi.desktop
	#fi

	if [ -f /usr/share/applications/firefox.desktop ]; then
		FIND="Exec="
		REPLACE="Exec=env MOZ_ENABLE_WAYLAND=1"
		echo "Changing /usr/share/applications/firefox.desktop"
		sudo sed -i "s/$FIND/$REPLACE/g" /usr/share/applications/firefox.desktop
	fi
fi






